apiVersion: v1
kind: Secret
metadata:
  name: yapipt-env
type: Opaque
stringData:
  SERVER_TCP_PORT: "8080" 
  DB_NAME: yapipt
  DB_PASSWORD: password
  DB_USER: appuser

---

apiVersion: v1
kind: Secret
metadata:
  name: yapipt-db-env
type: Opaque
stringData:
  POSTGRES_PASSWORD: password

---

apiVersion: v1
kind: Pod
metadata:
  name: yapipt
  labels:
    app: yapipt
spec:
  restartPolicy: Always
  containers:

    - name: db
      image: "docker.io/library/postgres:latest"
      resources:
        limits:
          cpu: "0.25"
          memory: "512Mi"
      envFrom:
        - secretRef:
            name: yapipt-db-env
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: db-data
          mountPath: /var/lib/postgresql
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d/init.sql
          readOnly: true

    - name: redis
      image: "docker.io/library/redis:latest"
      resources:
        limits:
          cpu: "0.1"
          memory: "128Mi"
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true

    - name: nginx
      image: "localhost/yapipt-nginx"
      resources:
        limits:
          cpu: "0.15"
          memory: "64Mi"
      ports:
        - containerPort: 443
          hostPort: 8080
          protocol: TCP
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: frontend
          mountPath: /usr/share/nginx/html/
          readOnly: true
        - name: nginxconf
          mountPath: /etc/nginx/nginx.conf
          readOnly: true
        - name: nginxcerts
          mountPath: /etc/nginx/certs

    - name: backend
      image: "localhost/yapipt-backend"
      resources:
        limits:
          cpu: "0.5"
          memory: "1024Mi"
      envFrom:
        - secretRef:
            name: yapipt-env
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true

  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Kolkata
        type: File
    - name: frontend
      hostPath:
        path: ../public/
        type: DirectoryOrCreate
    - name: nginxconf
      hostPath:
        path: ./nginx.conf
        type: File
    - name: nginxcerts
      hostPath:
        path: ./certs
        type: DirectoryOrCreate
    - name: db-data
      hostPath:
        path: ./db-data
        type: DirectoryOrCreate
    - name: db-init
      hostPath:
        path: ../db/init.sql
        type: File

