apiVersion: v1
kind: Pod
metadata:
  name: yapipt
  labels:
    app: yapipt
spec:
  restartPolicy: Always
  containers:
    - name: backend
      image: "localhost/yapipt-backend"
      resources:
        limits:
          cpu: "250m"
          memory: "256Mi"
      envFrom:
        - secretRef:
            name: yapipt-env
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true

    - name: nginx
      image: "localhost/yapipt-nginx"
      resources:
        limits:
          cpu: "200m"
          memory: "128Mi"
      ports:
        - containerPort: 443
          hostPort: 8080
          protocol: TCP
      volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: frontend
          mountPath: /usr/share/nginx/html/
          readOnly: true
        - name: nginxconf
          mountPath: /etc/nginx/nginx.conf
          readOnly: true
        - name: nginxcerts
          mountPath: /etc/nginx/certs

  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Kolkata
        type: File
    - name: frontend
      hostPath:
        path: ../public/
        type: DirectoryOrCreate
    - name: nginxconf
      hostPath:
        path: ./nginx.conf
        type: File
    - name: nginxcerts
      hostPath:
        path: ./certs
        type: DirectoryOrCreate
